// src/app/service/game.service.ts
import { Injectable } from '@angular/core';
import { BehaviorSubject } from 'rxjs';
import { Player } from '../interfaces/player';

interface WordEntry {
  secretWord: string;
  hintWord: string;
}

@Injectable({
  providedIn: 'root',
})
export class GameService {
  private playersSubject = new BehaviorSubject<Player[]>([]);
  players$ = this.playersSubject.asObservable();

  private secretWordSubject = new BehaviorSubject<string>('');
  secretWord$ = this.secretWordSubject.asObservable();

  private currentTurnIndexSubject = new BehaviorSubject<number>(0);
  currentTurnIndex$ = this.currentTurnIndexSubject.asObservable();

  private gamePhaseSubject = new BehaviorSubject<'setup' | 'reveal' | 'discussion' | 'resolved'>('setup');
  gamePhase$ = this.gamePhaseSubject.asObservable();

  // NEU: Subject für den Startspieler der Diskussion
  private discussionStartingPlayerNameSubject = new BehaviorSubject<string | null>(null);
  discussionStartingPlayerName$ = this.discussionStartingPlayerNameSubject.asObservable();

  private availableWords: WordEntry[] = [
    { secretWord: 'Sonne', hintWord: 'Scheint am Tag' },
    { secretWord: 'Baum', hintWord: 'Steht im Wald' },
    { secretWord: 'Haus', hintWord: 'Wo man wohnt' },
    { secretWord: 'Ball', hintWord: 'Zum Spielen' },
    { secretWord: 'Apfel', hintWord: 'Rotes Obst' },
    { secretWord: 'Hund', hintWord: 'Macht wau' },
    { secretWord: 'Katze', hintWord: 'Macht miau' },
    { secretWord: 'Wasser', hintWord: 'Zum Trinken' },
    { secretWord: 'Buch', hintWord: 'Zum Lesen' },
    { secretWord: 'Auto', hintWord: 'Fährt auf der Straße' },
    { secretWord: 'Bett', hintWord: 'Zum Schlafen' },
    { secretWord: 'Tisch', hintWord: 'Zum Essen' },
    { secretWord: 'Stuhl', hintWord: 'Zum Sitzen' },
    { secretWord: 'Tür', hintWord: 'Zum Öffnen' },
    { secretWord: 'Fenster', hintWord: 'Zum Raussehen' },
    { secretWord: 'Uhr', hintWord: 'Zeigt die Zeit' },
    { secretWord: 'Telefon', hintWord: 'Zum Anrufen' },
    { secretWord: 'Geld', hintWord: 'Zum Bezahlen' },
    { secretWord: 'Schule', hintWord: 'Wo man lernt' },
    { secretWord: 'Essen', hintWord: 'Nahrung aufnehmen' },
    { secretWord: 'Trinken', hintWord: 'Flüssigkeit aufnehmen' },
    { secretWord: 'Licht', hintWord: 'Macht hell' },
    { secretWord: 'Dunkel', hintWord: 'Kein Licht' },
    { secretWord: 'Tag', hintWord: 'Hell' },
    { secretWord: 'Nacht', hintWord: 'Dunkel' },
    { secretWord: 'Kind', hintWord: 'Kleiner Mensch' },
    { secretWord: 'Mann', hintWord: 'Erwachsener Junge' },
    { secretWord: 'Frau', hintWord: 'Erwachsenes Mädchen' },
    { secretWord: 'Familie', hintWord: 'Eltern und Kinder' },
    { secretWord: 'Freund', hintWord: 'Gute Bekanntschaft' },
    { secretWord: 'Stadt', hintWord: 'Großer Ort' },
    { secretWord: 'Dorf', hintWord: 'Kleiner Ort' },
    { secretWord: 'Straße', hintWord: 'Zum Fahren' },
    { secretWord: 'Weg', hintWord: 'Zum Gehen' },
    { secretWord: 'Fluss', hintWord: 'Fließendes Gewässer' },
    { secretWord: 'Berg', hintWord: 'Sehr hoch' },
    { secretWord: 'Meer', hintWord: 'Großes Wasser' },
    { secretWord: 'Fisch', hintWord: 'Schwimmt im Wasser' },
    { secretWord: 'Vogel', hintWord: 'Fliegt am Himmel' },
    { secretWord: 'Blume', hintWord: 'Wächst im Garten' },
    { secretWord: 'Gras', hintWord: 'Grün auf Boden' },
    { secretWord: 'Himmel', hintWord: 'Über uns' },
    { secretWord: 'Wolke', hintWord: 'Am Himmel' },
    { secretWord: 'Regen', hintWord: 'Wasser von oben' },
    { secretWord: 'Schnee', hintWord: 'Weiß im Winter' },
    { secretWord: 'Wind', hintWord: 'Bewegt Luft' },
    { secretWord: 'Feuer', hintWord: 'Macht warm' },
    { secretWord: 'Luft', hintWord: 'Zum Atmen' },
    { secretWord: 'Erde', hintWord: 'Unser Planet' },
    { secretWord: 'Stein', hintWord: 'Hartes Stück' },
    { secretWord: 'Holz', hintWord: 'Vom Baum' },
    { secretWord: 'Metall', hintWord: 'Glänzendes Material' },
    { secretWord: 'Plastik', hintWord: 'Leichtes Material' },
    { secretWord: 'Stoff', hintWord: 'Für Kleidung' },
    { secretWord: 'Glas', hintWord: 'Durchsichtiges Material' },
    { secretWord: 'Papier', hintWord: 'Zum Schreiben' },
    { secretWord: 'Stift', hintWord: 'Zum Schreiben' },
    { secretWord: 'Farbe', hintWord: 'Bunt' },
    { secretWord: 'Schere', hintWord: 'Zum Schneiden' },
    { secretWord: 'Messer', hintWord: 'Zum Schneiden' },
    { secretWord: 'Gabel', hintWord: 'Zum Aufspießen' },
    { secretWord: 'Löffel', hintWord: 'Zum Schöpfen' },
    { secretWord: 'Teller', hintWord: 'Zum Essen' },
    { secretWord: 'Tasse', hintWord: 'Für Getränke' },
    { secretWord: 'Flasche', hintWord: 'Für Getränke' },
    { secretWord: 'Korb', hintWord: 'Zum Tragen' },
    { secretWord: 'Tasche', hintWord: 'Zum Tragen' },
    { secretWord: 'Schuh', hintWord: 'Für den Fuß' },
    { secretWord: 'Socken', hintWord: 'Für die Füße' },
    { secretWord: 'Hose', hintWord: 'Zum Anziehen' },
    { secretWord: 'Hemd', hintWord: 'Oberteil' },
    { secretWord: 'Jacke', hintWord: 'Wärmt' },
    { secretWord: 'Mütze', hintWord: 'Für den Kopf' },
    { secretWord: 'Hand', hintWord: 'Zum Greifen' },
    { secretWord: 'Fuß', hintWord: 'Zum Laufen' },
    { secretWord: 'Kopf', hintWord: 'Oben am Körper' },
    { secretWord: 'Auge', hintWord: 'Zum Sehen' },
    { secretWord: 'Nase', hintWord: 'Zum Riechen' },
    { secretWord: 'Mund', hintWord: 'Zum Sprechen' },
    { secretWord: 'Ohr', hintWord: 'Zum Hören' },
    { secretWord: 'Haar', hintWord: 'Auf dem Kopf' },
    { secretWord: 'Zahn', hintWord: 'Im Mund' },
    { secretWord: 'Haut', hintWord: 'Über dem Körper' },
    { secretWord: 'Herz', hintWord: 'Pumpt Blut' },
    { secretWord: 'Blut', hintWord: 'Rot im Körper' },
    { secretWord: 'Knochen', hintWord: 'Im Körper' },
    { secretWord: 'Arzt', hintWord: 'Hilft bei Krankheit' },
    { secretWord: 'Krank', hintWord: 'Nicht gesund' },
    { secretWord: 'Gesund', hintWord: 'Nicht krank' },
    { secretWord: 'Schmerz', hintWord: 'Tut weh' },
    { secretWord: 'Lachen', hintWord: 'Freude zeigen' },
    { secretWord: 'Weinen', hintWord: 'Trauer zeigen' },
    { secretWord: 'Sprechen', hintWord: 'Reden' },
    { secretWord: 'Hören', hintWord: 'Töne wahrnehmen' },
    { secretWord: 'Sehen', hintWord: 'Bilder wahrnehmen' },
    { secretWord: 'Riechen', hintWord: 'Gerüche wahrnehmen' },
    { secretWord: 'Fühlen', hintWord: 'Tasten' },
    { secretWord: 'Denken', hintWord: 'Nachdenken' },
    { secretWord: 'Lernen', hintWord: 'Wissen erwerben' },
    { secretWord: 'Spielen', hintWord: 'Freizeitaktivität' },
    { secretWord: 'Arbeiten', hintWord: 'Job machen' },
    { secretWord: 'Schlafen', hintWord: 'Ruhen' },
    { secretWord: 'Wach', hintWord: 'Nicht müde' },
    { secretWord: 'Müde', hintWord: 'Braucht Schlaf' },
    { secretWord: 'Warm', hintWord: 'Angenehme Temperatur' },
    { secretWord: 'Kalt', hintWord: 'Niedrige Temperatur' },
    { secretWord: 'Groß', hintWord: 'Nicht klein' },
    { secretWord: 'Klein', hintWord: 'Nicht groß' },
    { secretWord: 'Lang', hintWord: 'Nicht kurz' },
    { secretWord: 'Kurz', hintWord: 'Nicht lang' },
    { secretWord: 'Alt', hintWord: 'Nicht jung' },
    { secretWord: 'Neu', hintWord: 'Nicht alt' },
    { secretWord: 'Schnell', hintWord: 'Hohe Geschwindigkeit' },
    { secretWord: 'Langsam', hintWord: 'Niedrige Geschwindigkeit' },
    { secretWord: 'Gut', hintWord: 'Positiv' },
    { secretWord: 'Schlecht', hintWord: 'Negativ' },
    { secretWord: 'Ja', hintWord: 'Zustimmung' },
    { secretWord: 'Nein', hintWord: 'Ablehnung' },
    { secretWord: 'Bitte', hintWord: 'Höfliche Frage' },
    { secretWord: 'Danke', hintWord: 'Dankbarkeit' },
    { secretWord: 'Hallo', hintWord: 'Begrüßung' },
    { secretWord: 'Tschüss', hintWord: 'Verabschiedung' },
    { secretWord: 'Hilfe', hintWord: 'Unterstützung' },
    { secretWord: 'Leise', hintWord: 'Wenig Lärm' },
    { secretWord: 'Laut', hintWord: 'Viel Lärm' },
    { secretWord: 'Frage', hintWord: 'Wissen wollen' },
    { secretWord: 'Antwort', hintWord: 'Wissen geben' },
    { secretWord: 'Problem', hintWord: 'Herausforderung' },
    { secretWord: 'Lösung', hintWord: 'Antwort auf Problem' },
    { secretWord: 'Glück', hintWord: 'Frohes Gefühl' },
    { secretWord: 'Trauer', hintWord: 'Schlechtes Gefühl' },
    { secretWord: 'Angst', hintWord: 'Furcht' },
    { secretWord: 'Liebe', hintWord: 'Starkes Gefühl' },
    { secretWord: 'Hass', hintWord: 'Starkes negatives Gefühl' },
    { secretWord: 'Wut', hintWord: 'Starkes Ärgergefühl' },
    { secretWord: 'Zeit', hintWord: 'Vergeht' },
    { secretWord: 'Heute', hintWord: 'Dieser Tag' },
    { secretWord: 'Gestern', hintWord: 'Letzter Tag' },
    { secretWord: 'Morgen', hintWord: 'Nächster Tag' },
    { secretWord: 'Woche', hintWord: 'Sieben Tage' },
    { secretWord: 'Monat', hintWord: 'Vier Wochen' },
    { secretWord: 'Jahr', hintWord: 'Zwölf Monate' },
    { secretWord: 'Sommer', hintWord: 'Warm' },
    { secretWord: 'Winter', hintWord: 'Kalt und Schnee' },
    { secretWord: 'Frühling', hintWord: 'Pflanzen wachsen' },
    { secretWord: 'Herbst', hintWord: 'Blätter fallen' },
    { secretWord: 'Morgen (Tageszeit)', hintWord: 'Beginn des Tages' },
    { secretWord: 'Abend', hintWord: 'Ende des Tages' },
    { secretWord: 'Mittag', hintWord: 'Mitte des Tages' },
    { secretWord: 'Frühstück', hintWord: 'Morgenessen' },
    { secretWord: 'Mittagessen', hintWord: 'Essen am Mittag' },
    { secretWord: 'Abendessen', hintWord: 'Essen am Abend' },
    { secretWord: 'Kaffee', hintWord: 'Heißes Getränk' },
    { secretWord: 'Tee', hintWord: 'Heißes Getränk' },
    { secretWord: 'Milch', hintWord: 'Weißes Getränk' },
    { secretWord: 'Brot', hintWord: 'Zum Belegen' },
    { secretWord: 'Käse', hintWord: 'Milchprodukt' },
    { secretWord: 'Fleisch', hintWord: 'Vom Tier' },
    { secretWord: 'Gemüse', hintWord: 'Grünes Essen' },
    { secretWord: 'Obst', hintWord: 'Süße Früchte' },
    { secretWord: 'Reis', hintWord: 'Kleine Körner' },
    { secretWord: 'Nudel', hintWord: 'Lange Teigware' },
    { secretWord: 'Pizza', hintWord: 'Runder Teig mit Belag' },
    { secretWord: 'Salat', hintWord: 'Grünes Gericht' },
    { secretWord: 'Suppe', hintWord: 'Flüssiges Essen' },
    { secretWord: 'Kuchen', hintWord: 'Süßes Gebäck' },
    { secretWord: 'Schokolade', hintWord: 'Süßigkeit' },
    { secretWord: 'Eis (Speise)', hintWord: 'Kaltes Dessert' },
    { secretWord: 'Sport', hintWord: 'Körperliche Aktivität' },
    { secretWord: 'Schwimmen', hintWord: 'Im Wasser bewegen' },
    { secretWord: 'Laufen', hintWord: 'Schnell gehen' },
    { secretWord: 'Springen', hintWord: 'Sich abstoßen' },
    { secretWord: 'Singen', hintWord: 'Melodisch sprechen' },
    { secretWord: 'Tanzen', hintWord: 'Bewegung zur Musik' },
    { secretWord: 'Malen', hintWord: 'Bilder erstellen' },
    { secretWord: 'Zeichnen', hintWord: 'Linien machen' },
    { secretWord: 'Lesen', hintWord: 'Bücher verstehen' },
    { secretWord: 'Schreiben', hintWord: 'Buchstaben machen' },
    { secretWord: 'Rechnen', hintWord: 'Mit Zahlen umgehen' },
    { secretWord: 'Zahl', hintWord: 'Für Mengen' },
    { secretWord: 'Buchstabe', hintWord: 'Teil eines Wortes' },
    { secretWord: 'Wort', hintWord: 'Teil der Sprache' },
    { secretWord: 'Satz', hintWord: 'Reihe von Wörtern' },
    { secretWord: 'Geschichte', hintWord: 'Was früher war' },
    { secretWord: 'Land', hintWord: 'Staat oder Erde' },
    { secretWord: 'Welt', hintWord: 'Unser Planet' },
    { secretWord: 'Flugzeug', hintWord: 'Fliegt' },
    { secretWord: 'Zug', hintWord: 'Fährt auf Schienen' },
    { secretWord: 'Bus', hintWord: 'Großes Auto' },
    { secretWord: 'Fahrrad', hintWord: 'Zwei Räder' },
    { secretWord: 'Krankenhaus', hintWord: 'Für Kranke' },
    { secretWord: 'Polizei', hintWord: 'Für Ordnung' },
    { secretWord: 'Feuerwehr', hintWord: 'Löscht Brände' },
    { secretWord: 'Arbeit', hintWord: 'Tätigkeit' },
    { secretWord: 'Feier', hintWord: 'Party' },
    { secretWord: 'Geschenk', hintWord: 'Geschenktes' },
    { secretWord: 'Lied', hintWord: 'Gesungene Musik' },
    { secretWord: 'Instrument', hintWord: 'Zum Musizieren' },
    { secretWord: 'Gitarre', hintWord: 'Saiteninstrument' },
    { secretWord: 'Klavier', hintWord: 'Tasteninstrument' },
    { secretWord: 'Film', hintWord: 'Bewegte Bilder' },
    { secretWord: 'Kino', hintWord: 'Für Filme' },
    { secretWord: 'Zoo', hintWord: 'Für Tiere' },
    { secretWord: 'Garten', hintWord: 'Grünfläche' },
    { secretWord: 'Schirm', hintWord: 'Schutz vor Regen/Sonne' },
    { secretWord: 'Computer', hintWord: 'Zum Arbeiten und Spielen' },
    { secretWord: 'Handy', hintWord: 'Kleines Telefon' },
    { secretWord: 'Internet', hintWord: 'Weltweites Netz' },
    { secretWord: 'Spiel', hintWord: 'Freizeitaktivität' },
    { secretWord: 'Buchstabe', hintWord: 'Zeichen' },
    { secretWord: 'Foto', hintWord: 'Gemachtes Bild' },
    { secretWord: 'Regel', hintWord: 'Was man tun soll' },
    { secretWord: 'Gesetz', hintWord: 'Wichtige Regel' },
    { secretWord: 'Wahrheit', hintWord: 'Was stimmt' },
    { secretWord: 'Lüge', hintWord: 'Was nicht stimmt' },
    { secretWord: 'Fragen', hintWord: 'Information einholen' },
    { secretWord: 'Antworten', hintWord: 'Information geben' },
    { secretWord: 'Suchen', hintWord: 'Finden wollen' },
    { secretWord: 'Finden', hintWord: 'Entdecken' },
    { secretWord: 'Verlieren', hintWord: 'Nicht finden' },
    { secretWord: 'Gewinnen', hintWord: 'Besser sein' },
    { secretWord: 'Verlieren (Spiel)', hintWord: 'Schlechter sein' },
    { secretWord: 'Starten', hintWord: 'Beginnen' },
    { secretWord: 'Stoppen', hintWord: 'Anhalten' },
    { secretWord: 'Öffnen', hintWord: 'Aufmachen' },
    { secretWord: 'Schließen', hintWord: 'Zumachen' },
    { secretWord: 'Kaufen', hintWord: 'Geld ausgeben' },
    { secretWord: 'Verkaufen', hintWord: 'Geld einnehmen' },
    { secretWord: 'Schenken', hintWord: 'Etwas geben' },
    { secretWord: 'Bekommen', hintWord: 'Etwas erhalten' },
    { secretWord: 'Geben', hintWord: 'Etwas überreichen' },
    { secretWord: 'Nehmen', hintWord: 'Etwas an sich nehmen' },
    { secretWord: 'Zeigen', hintWord: 'Darstellen' },
    { secretWord: 'Warten', hintWord: 'Nicht gehen' },
    { secretWord: 'Helfen', hintWord: 'Unterstützen' },
    { secretWord: 'Dunkelheit', hintWord: 'Kein Licht' },
    { secretWord: 'Stille', hintWord: 'Kein Geräusch' },
    { secretWord: 'Geräusch', hintWord: 'Was man hört' },
    { secretWord: 'Duft', hintWord: 'Angenehmer Geruch' },
    { secretWord: 'Geruch', hintWord: 'Was man riecht' },
    { secretWord: 'Geschmack', hintWord: 'Was man schmeckt' },
    { secretWord: 'Süß', hintWord: 'Zuckergeschmack' },
    { secretWord: 'Sauer', hintWord: 'Zitronengeschmack' },
    { secretWord: 'Salzig', hintWord: 'Salzgeschmack' },
    { secretWord: 'Scharf', hintWord: 'Chili-Geschmack' },
    { secretWord: 'Rot', hintWord: 'Starke Farbe' },
    { secretWord: 'Blau', hintWord: 'Himmelsfarbe' },
    { secretWord: 'Grün', hintWord: 'Grasfarbe' },
    { secretWord: 'Gelb', hintWord: 'Sonnenfarbe' },
    { secretWord: 'Schwarz', hintWord: 'Dunkelste Farbe' },
    { secretWord: 'Weiß', hintWord: 'Hellste Farbe' },
    { secretWord: 'Grau', hintWord: 'Zwischen Schwarz und Weiß' },
    { secretWord: 'Braun', hintWord: 'Erdfarbe' },
    { secretWord: 'Orange', hintWord: 'Fruchtfarbe' },
    { secretWord: 'Lila', hintWord: 'Mischfarbe' },
    { secretWord: 'Rosa', hintWord: 'Helles Rot' },
    { secretWord: 'Form', hintWord: 'Gestalt' },
    { secretWord: 'Rund', hintWord: 'Kreisförmig' },
    { secretWord: 'Eckig', hintWord: 'Hat Ecken' },
    { secretWord: 'Weich', hintWord: 'Angenehm zu berühren' },
    { secretWord: 'Hart', hintWord: 'Nicht weich' },
    { secretWord: 'Heiß', hintWord: 'Sehr warm' },
    { secretWord: 'Kalt', hintWord: 'Sehr kalt' },
    { secretWord: 'Frisch', hintWord: 'Neu und kühl' },
    { secretWord: 'Schön', hintWord: 'Angenehm anzusehen' },
    { secretWord: 'Hässlich', hintWord: 'Nicht schön' },
    { secretWord: 'Maus (Tier)', hintWord: 'Kleines Nagetier' },
    { secretWord: 'Vogel', hintWord: 'Fliegt' },
    { secretWord: 'Tier', hintWord: 'Lebewesen' },
    { secretWord: 'Blatt', hintWord: 'Am Baum' },
    { secretWord: 'Wurzel', hintWord: 'Unter der Erde' },
    { secretWord: 'Stamm', hintWord: 'Teil vom Baum' },
    { secretWord: 'Ast', hintWord: 'Zweig vom Baum' },
    { secretWord: 'Blüte', hintWord: 'Blume' },
    { secretWord: 'Frucht', hintWord: 'Vom Baum' },
    { secretWord: 'Samen', hintWord: 'Wird Pflanze' },
    { secretWord: 'Erde', hintWord: 'Für Pflanzen' },
    { secretWord: 'Schlamm', hintWord: 'Nasse Erde' },
    { secretWord: 'Sand', hintWord: 'Am Strand' },
    { secretWord: 'Schnee', hintWord: 'Weiß im Winter' },
    { secretWord: 'Eis', hintWord: 'Gefrorenes Wasser' },
    { secretWord: 'Nebel', hintWord: 'Dichte Luft' },
    { secretWord: 'Blitz', hintWord: 'Licht am Himmel' },
    { secretWord: 'Donner', hintWord: 'Lautes Geräusch' },
    { secretWord: 'Regenbogen', hintWord: 'Bunte Brücke' },
    { secretWord: 'Strand', hintWord: 'Am Meer' },
    { secretWord: 'See', hintWord: 'Großes Wasser' },
    { secretWord: 'Insel', hintWord: 'Land im Wasser' },
    { secretWord: 'Wüste', hintWord: 'Sand ohne Wasser' },
    { secretWord: 'Wald', hintWord: 'Voller Bäume' },
    { secretWord: 'Küste', hintWord: 'Am Meer' },
    { secretWord: 'Hafen', hintWord: 'Für Schiffe' },
    { secretWord: 'Flughafen', hintWord: 'Für Flugzeuge' },
    { secretWord: 'Bahnhof', hintWord: 'Für Züge' },
    { secretWord: 'Haltestelle', hintWord: 'Für Bus' },
    { secretWord: 'Ampel', hintWord: 'Regelt Verkehr' },
    { secretWord: 'Kreuzung', hintWord: 'Straßen treffen sich' },
    { secretWord: 'Brücke', hintWord: 'Über den Fluss' },
    { secretWord: 'Tunnel', hintWord: 'Durch den Berg' },
    { secretWord: 'Kirche', hintWord: 'Gebäude zum Beten' },
    { secretWord: 'Moschee', hintWord: 'Gebäude zum Beten' },
    { secretWord: 'Synagoge', hintWord: 'Gebäude zum Beten' },
    { secretWord: 'Tempel', hintWord: 'Heiliger Ort' },
    { secretWord: 'Museum', hintWord: 'Für Kunst' },
    { secretWord: 'Bibliothek', hintWord: 'Für Bücher' },
    { secretWord: 'Supermarkt', hintWord: 'Zum Einkaufen' },
    { secretWord: 'Restaurant', hintWord: 'Zum Essen gehen' },
    { secretWord: 'Café', hintWord: 'Für Kaffee' },
    { secretWord: 'Bäckerei', hintWord: 'Für Brot' },
    { secretWord: 'Metzgerei', hintWord: 'Für Fleisch' },
    { secretWord: 'Apotheke', hintWord: 'Für Medikamente' },
    { secretWord: 'Post', hintWord: 'Für Briefe' },
    { secretWord: 'Bank', hintWord: 'Für Geld' },
    { secretWord: 'Polizeiwache', hintWord: 'Polizei-Gebäude' },
    { secretWord: 'Feuerwache', hintWord: 'Feuerwehr-Gebäude' },
    { secretWord: 'Hotel', hintWord: 'Zum Schlafen' },
    { secretWord: 'Krankenzimmer', hintWord: 'Im Krankenhaus' },
    { secretWord: 'Büro', hintWord: 'Arbeitsplatz' },
    { secretWord: 'Fabrik', hintWord: 'Macht Produkte' },
    { secretWord: 'Lagerhalle', hintWord: 'Für Waren' },
    { secretWord: 'Geschäft', hintWord: 'Zum Kaufen' },
    { secretWord: 'Kasse', hintWord: 'Wo man bezahlt' },
    { secretWord: 'Einkaufswagen', hintWord: 'Zum Schieben' },
    { secretWord: 'Tüte', hintWord: 'Für Einkäufe' },
    { secretWord: 'Quittung', hintWord: 'Beleg' },
    { secretWord: 'Preis', hintWord: 'Wie viel es kostet' },
    { secretWord: 'Rabatt', hintWord: 'Weniger Preis' },
    { secretWord: 'Angebot', hintWord: 'Besonderer Preis' },
    { secretWord: 'Werbung', hintWord: 'Macht Produkt bekannt' },
    { secretWord: 'Nachricht', hintWord: 'Information' },
    { secretWord: 'Zeitung', hintWord: 'Mit Nachrichten' },
    { secretWord: 'Radio', hintWord: 'Macht Musik und Nachrichten' },
    { secretWord: 'Fernsehen', hintWord: 'Für Filme und Shows' },
    { secretWord: 'Bildschirm', hintWord: 'Zeigt Bilder' },
    { secretWord: 'Lautsprecher', hintWord: 'Macht Ton' },
    { secretWord: 'Mikrofon', hintWord: 'Nimmt Ton auf' },
    { secretWord: 'Kopfhörer', hintWord: 'Für die Ohren' },
    { secretWord: 'Batterie', hintWord: 'Gibt Strom' },
    { secretWord: 'Kabel', hintWord: 'Verbindet' },
    { secretWord: 'Stecker', hintWord: 'Passt in Steckdose' },
    { secretWord: 'Steckdose', hintWord: 'Gibt Strom' },
    { secretWord: 'Schalter', hintWord: 'An oder aus' },
    { secretWord: 'Glühbirne', hintWord: 'Macht Licht' },
    { secretWord: 'Lampe', hintWord: 'Macht Licht' },
    { secretWord: 'Spiegel', hintWord: 'Zeigt dein Bild' },
    { secretWord: 'Uhrzeit', hintWord: 'Genauer Zeitpunkt' },
    { secretWord: 'Datum', hintWord: 'Tag, Monat, Jahr' },
    { secretWord: 'Kalender', hintWord: 'Zeigt Tage' },
    { secretWord: 'Ferien', hintWord: 'Freie Tage' },
    { secretWord: 'Urlaub', hintWord: 'Reise' },
    { secretWord: 'Reise', hintWord: 'Unterwegs sein' },
    { secretWord: 'Pass', hintWord: 'Reisedokument' },
    { secretWord: 'Ticket', hintWord: 'Fahrkarte' },
    { secretWord: 'Gepäck', hintWord: 'Koffer' },
    { secretWord: 'Koffer', hintWord: 'Für Kleidung' },
    { secretWord: 'Rucksack', hintWord: 'Für den Rücken' },
    { secretWord: 'Landkarte', hintWord: 'Zeigt Weg' },
    { secretWord: 'Kompass', hintWord: 'Zeigt Richtung' },
    { secretWord: 'Taschenlampe', hintWord: 'Macht Licht im Dunkeln' },
    { secretWord: 'Wanderung', hintWord: 'Zu Fuß gehen' },
    { secretWord: 'Picknick', hintWord: 'Essen im Freien' },
    { secretWord: 'Zelt', hintWord: 'Stoffhaus' },
    { secretWord: 'Schlafsack', hintWord: 'Zum Schlafen draußen' },
    { secretWord: 'Lagerfeuer', hintWord: 'Feuer draußen' },
    { secretWord: 'Sonnenschein', hintWord: 'Wenn Sonne scheint' },
    { secretWord: 'Regenbogen', hintWord: 'Bunte Brücke am Himmel' },
    { secretWord: 'Windstärke', hintWord: 'Wie stark Wind ist' },
    { secretWord: 'Temperatur', hintWord: 'Wie warm oder kalt' },
    { secretWord: 'Wetter', hintWord: 'Sonne, Regen, Schnee' },
    { secretWord: 'Klima', hintWord: 'Wetter über lange Zeit' },
    { secretWord: 'Umwelt', hintWord: 'Natur um uns' },
    { secretWord: 'Müll', hintWord: 'Abfall' },
    { secretWord: 'Recycling', hintWord: 'Wiederverwerten' },
    { secretWord: 'Verschmutzung', hintWord: 'Dreckig machen' },
    { secretWord: 'Sauberkeit', hintWord: 'Reinheit' },
    { secretWord: 'Geruch', hintWord: 'Was man riecht' },
    { secretWord: 'Geschmack', hintWord: 'Was man schmeckt' },
    { secretWord: 'Gesang', hintWord: 'Musik mit Stimme' },
    { secretWord: 'Tanz', hintWord: 'Bewegung zur Musik' },
    { secretWord: 'Lied', hintWord: 'Gesungene Musik' },
    { secretWord: 'Konzert', hintWord: 'Live Musik' },
    { secretWord: 'Bühne', hintWord: 'Wo gespielt wird' },
    { secretWord: 'Applaus', hintWord: 'Händeklatschen' },
    { secretWord: 'Vorhang', hintWord: 'Vor der Bühne' },
    { secretWord: 'Schauspieler', hintWord: 'Spielt Rollen' },
    { secretWord: 'Publikum', hintWord: 'Zuschauer' },
    { secretWord: 'Sportplatz', hintWord: 'Für Sport' },
    { secretWord: 'Tor', hintWord: 'Im Fußball' },
    { secretWord: 'Ball', hintWord: 'Rundes Spielgerät' },
    { secretWord: 'Spieler', hintWord: 'Macht Sport' },
    { secretWord: 'Trainer', hintWord: 'Leitet Sportler' },
    { secretWord: 'Sieg', hintWord: 'Gewinnen' },
    { secretWord: 'Niederlage', hintWord: 'Verlieren' },
    { secretWord: 'Medaille', hintWord: 'Belohnung' },
    { secretWord: 'Pokal', hintWord: 'Trophäe' },
    { secretWord: 'Team', hintWord: 'Gruppe' },
    { secretWord: 'Regel', hintWord: 'Was erlaubt ist' },
    { secretWord: 'Strafen', hintWord: 'Wenn man Regel bricht' },
    { secretWord: 'Fair Play', hintWord: 'Faires Spiel' },
    { secretWord: 'Fan', hintWord: 'Begeisterter Anhänger' },
    { secretWord: 'Schiedsrichter', hintWord: 'Regelwächter' },
    { secretWord: 'Medizin', hintWord: 'Heilkunde' },
    { secretWord: 'Krankheit', hintWord: 'Nicht gesund' },
    { secretWord: 'Arzneimittel', hintWord: 'Medikament' },
    { secretWord: 'Behandlung', hintWord: 'Therapie' },
    { secretWord: 'Operation', hintWord: 'Eingriff am Körper' },
    { secretWord: 'Gesundheit', hintWord: 'Wohlbefinden' },
    { secretWord: 'Arztpraxis', hintWord: 'Wo Arzt arbeitet' },
    { secretWord: 'Krankenbett', hintWord: 'Im Krankenhaus' },
    { secretWord: 'Pfleger', hintWord: 'Hilft Kranken' },
    { secretWord: 'Impfung', hintWord: 'Schutz vor Krankheit' },
    { secretWord: 'Virus', hintWord: 'Kleiner Krankheitserreger' },
    { secretWord: 'Bakterium', hintWord: 'Kleinstlebewesen' },
    { secretWord: 'Gehirn', hintWord: 'Denkorgan' },
    { secretWord: 'Herzschlag', hintWord: 'Puls' },
    { secretWord: 'Atmung', hintWord: 'Ein- und Ausatmen' },
    { secretWord: 'Körper', hintWord: 'Menschlicher Leib' },
    { secretWord: 'Organ', hintWord: 'Teil vom Körper' },
    { secretWord: 'Zelle', hintWord: 'Kleinste Einheit' },
    { secretWord: 'Gen', hintWord: 'Erbanlage' },
    { secretWord: 'Natur', hintWord: 'Alles was wächst' },
    { secretWord: 'Pflanze', hintWord: 'Wächst in Natur' },
    { secretWord: 'Tier', hintWord: 'Lebewesen' },
    { secretWord: 'Waldtier', hintWord: 'Tier im Wald' },
    { secretWord: 'Haustier', hintWord: 'Tier zu Hause' },
    { secretWord: 'Wildtier', hintWord: 'Tier in Freiheit' },
    { secretWord: 'Insekt', hintWord: 'Kleines Krabbeltier' },
    { secretWord: 'Vogelart', hintWord: 'Art von Vogel' },
    { secretWord: 'Meerestier', hintWord: 'Tier im Meer' },
    { secretWord: 'Blattgrün', hintWord: 'Farbe der Blätter' },
    { secretWord: 'Wüste', hintWord: 'Sand ohne Wasser' },
    { secretWord: 'Gebirge', hintWord: 'Viele Berge' },
    { secretWord: 'Tal', hintWord: 'Zwischen Bergen' },
    { secretWord: 'Seeufer', hintWord: 'Am See' },
    { secretWord: 'Flussufer', hintWord: 'Am Fluss' },
    { secretWord: 'Ozean', hintWord: 'Sehr großes Meer' },
    { secretWord: 'Insel', hintWord: 'Land im Wasser' },
    { secretWord: 'Vulkan', hintWord: 'Spuckt Feuer' },
    { secretWord: 'Erdbeben', hintWord: 'Boden bebt' },
    { secretWord: 'Sonnensystem', hintWord: 'Planeten um Sonne' },
    { secretWord: 'Planet', hintWord: 'Himmelskörper' },
    { secretWord: 'Mond', hintWord: 'Leuchtet Nachts' },
    { secretWord: 'Stern', hintWord: 'Funkelt am Himmel' },
    { secretWord: 'Galaxie', hintWord: 'Viele Sterne' },
    { secretWord: 'Universum', hintWord: 'Alles' },
    { secretWord: 'Weltall', hintWord: 'Über uns' },
    { secretWord: 'Rakete', hintWord: 'Fliegt ins All' },
    { secretWord: 'Astronaut', hintWord: 'Reist ins All' },
    { secretWord: 'Satellit', hintWord: 'Fliegt um Erde' },
    { secretWord: 'Teleskop', hintWord: 'Sieht weit' },
    { secretWord: 'Mikroskop', hintWord: 'Sieht klein' },
    { secretWord: 'Chemie', hintWord: 'Stofflehre' },
    { secretWord: 'Physik', hintWord: 'Naturgesetze' },
    { secretWord: 'Biologie', hintWord: 'Lebenslehre' },
    { secretWord: 'Mathematik', hintWord: 'Zahlenlehre' },
    { secretWord: 'Sprache', hintWord: 'Zum Reden' },
    { secretWord: 'Geschichte', hintWord: 'Vergangenes' },
    { secretWord: 'Politik', hintWord: 'Regierung' },
    { secretWord: 'Wirtschaft', hintWord: 'Geld und Handel' },
    { secretWord: 'Gesetz', hintWord: 'Regeln für alle' },
    { secretWord: 'Gerechtigkeit', hintWord: 'Fairness' },
    { secretWord: 'Freiheit', hintWord: 'Tun was man will' },
    { secretWord: 'Frieden', hintWord: 'Kein Krieg' },
    { secretWord: 'Krieg', hintWord: 'Kampf' },
    { secretWord: 'Demokratie', hintWord: 'Volksherrschaft' },
    { secretWord: 'Wahlen', hintWord: 'Abstimmen' },
    { secretWord: 'Regierung', hintWord: 'Leitet Land' },
    { secretWord: 'Bürger', hintWord: 'Einwohner' },
    { secretWord: 'Landwirt', hintWord: 'Bauer' },
    { secretWord: 'Soldat', hintWord: 'Kämpfer' },
    { secretWord: 'König', hintWord: 'Herrscher' },
    { secretWord: 'Königin', hintWord: 'Herrscherin' },
    { secretWord: 'Prinz', hintWord: 'Königssohn' },
    { secretWord: 'Prinzessin', hintWord: 'Königstochter' },
    { secretWord: 'Reichtum', hintWord: 'Viel Geld' },
    { secretWord: 'Armut', hintWord: 'Wenig Geld' },
    { secretWord: 'Hunger', hintWord: 'Braucht Essen' },
    { secretWord: 'Durst', hintWord: 'Braucht Trinken' },
    { secretWord: 'Kleidung', hintWord: 'Zum Anziehen' },
    { secretWord: 'Wohnung', hintWord: 'Ort zum Wohnen' },
    { secretWord: 'Eigentum', hintWord: 'Was jemandem gehört' },
    { secretWord: 'Arbeitgeber', hintWord: 'Gibt Arbeit' },
    { secretWord: 'Arbeitnehmer', hintWord: 'Nimmt Arbeit an' },
    { secretWord: 'Gehalt', hintWord: 'Lohn' },
    { secretWord: 'Steuer', hintWord: 'Geld für Staat' },
    { secretWord: 'Währung', hintWord: 'Geldart' },
    { secretWord: 'Banknote', hintWord: 'Geldschein' },
    { secretWord: 'Münze', hintWord: 'Kleines Geldstück' },
    { secretWord: 'Schuld', hintWord: 'Geld zurückzahlen' },
    { secretWord: 'Kredit', hintWord: 'Geld leihen' },
    { secretWord: 'Ersparnis', hintWord: 'Geld gespart' },
    { secretWord: 'Zinsen', hintWord: 'Geld für Leihe' },
    { secretWord: 'Markt', hintWord: 'Wo man kauft' },
    { secretWord: 'Handel', hintWord: 'Kaufen und Verkaufen' },
    { secretWord: 'Waren', hintWord: 'Produkte' },
    { secretWord: 'Dienstleistung', hintWord: 'Service' },
    { secretWord: 'Werbung', hintWord: 'Macht Produkt bekannt' },
    { secretWord: 'Kunde', hintWord: 'Käufer' },
    { secretWord: 'Verkäufer', hintWord: 'Verkauft' },
    { secretWord: 'Lieferung', hintWord: 'Bringt Ware' },
    { secretWord: 'Transport', hintWord: 'Waren bewegen' },
    { secretWord: 'Logistik', hintWord: 'Waren planen' },
    { secretWord: 'Lager', hintWord: 'Für Waren' },
    { secretWord: 'Fabrik', hintWord: 'Macht Produkte' },
    { secretWord: 'Maschine', hintWord: 'Arbeitet selbst' },
    { secretWord: 'Roboter', hintWord: 'Maschine' },
    { secretWord: 'Technik', hintWord: 'Neuigkeiten' },
    { secretWord: 'Innovation', hintWord: 'Neuerung' },
    { secretWord: 'Erfindung', hintWord: 'Etwas Neues' },
    { secretWord: 'Wissenschaft', hintWord: 'Wissen suchen' },
    { secretWord: 'Forschung', hintWord: 'Wissen finden' },
    { secretWord: 'Entdeckung', hintWord: 'Neues finden' },
    { secretWord: 'Studium', hintWord: 'An der Uni lernen' },
    { secretWord: 'Professor', hintWord: 'Lehrt an Uni' },
    { secretWord: 'Student', hintWord: 'Lernt an Uni' },
    { secretWord: 'Schüler', hintWord: 'Lernt in Schule' },
    { secretWord: 'Lehrer', hintWord: 'Lehrt in Schule' },
    { secretWord: 'Schulbuch', hintWord: 'Buch für Schule' },
    { secretWord: 'Tafel', hintWord: 'Zum Schreiben in Schule' },
    { secretWord: 'Kreide', hintWord: 'Zum Schreiben auf Tafel' },
    { secretWord: 'Stundenplan', hintWord: 'Plan für Schule' },
    { secretWord: 'Hausaufgaben', hintWord: 'Aufgaben für Zuhause' },
    { secretWord: 'Examen', hintWord: 'Prüfung' },
    { secretWord: 'Zeugnis', hintWord: 'Notenblatt' },
    { secretWord: 'Abschluss', hintWord: 'Ende der Schule' },
    { secretWord: 'Diplom', hintWord: 'Zeugnis von Uni' },
    { secretWord: 'Beruf', hintWord: 'Arbeit' },
    { secretWord: 'Karriere', hintWord: 'Berufsweg' },
    { secretWord: 'Pension', hintWord: 'Rente' },
    { secretWord: 'Ruhestand', hintWord: 'Nicht mehr arbeiten' },
    { secretWord: 'Hobby', hintWord: 'Freizeitbeschäftigung' },
    { secretWord: 'Sportart', hintWord: 'Art von Sport' },
    { secretWord: 'Musikstil', hintWord: 'Art von Musik' },
    { secretWord: 'Filmgenre', hintWord: 'Art von Film' },
    { secretWord: 'Buchgenre', hintWord: 'Art von Buch' },
    { secretWord: 'Reiseziel', hintWord: 'Wo man hinreist' },
    { secretWord: 'Sehenswürdigkeit', hintWord: 'Was man sehen muss' },
    { secretWord: 'Denkmal', hintWord: 'Zur Erinnerung' },
    { secretWord: 'Kunstwerk', hintWord: 'Gemaltes oder Gebautes' },
    { secretWord: 'Ausstellung', hintWord: 'Kunst zeigen' },
    { secretWord: 'Galerie', hintWord: 'Für Kunst' },
    { secretWord: 'Bühne', hintWord: 'Wo gespielt wird' },
    { secretWord: 'Publikum', hintWord: 'Zuschauer' },
    { secretWord: 'Applaus', hintWord: 'Händeklatschen' },
    { secretWord: 'Autogramm', hintWord: 'Unterschrift' },
    { secretWord: 'Fan', hintWord: 'Begeisterter Anhänger' },
    { secretWord: 'Star', hintWord: 'Berühmte Person' },
    { secretWord: 'Glückszahl', hintWord: 'Zahl die Glück bringt' },
    { secretWord: 'Farbe', hintWord: 'Bunt' },
    { secretWord: 'Form', hintWord: 'Gestalt' },
    { secretWord: 'Größe', hintWord: 'Wie groß etwas ist' },
    { secretWord: 'Gewicht', hintWord: 'Wie schwer etwas ist' },
    { secretWord: 'Geschwindigkeit', hintWord: 'Wie schnell etwas ist' },
    { secretWord: 'Lautstärke', hintWord: 'Wie laut etwas ist' },
    { secretWord: 'Temperatur', hintWord: 'Wie warm oder kalt etwas ist' },
    { secretWord: 'Geruch', hintWord: 'Was man riecht' },
    { secretWord: 'Geschmack', hintWord: 'Was man schmeckt' },
    { secretWord: 'Gefühl', hintWord: 'Emotion' },
    { secretWord: 'Gedanke', hintWord: 'Was man denkt' },
    { secretWord: 'Idee', hintWord: 'Gedanke' },
    { secretWord: 'Traum', hintWord: 'Bilder im Schlaf' },
    { secretWord: 'Erinnerung', hintWord: 'Was man sich merkt' },
    { secretWord: 'Zukunft', hintWord: 'Was kommt' },
    { secretWord: 'Vergangenheit', hintWord: 'Was war' },
    { secretWord: 'Gegenwart', hintWord: 'Jetzt' },
    { secretWord: 'Hoffnung', hintWord: 'Wunsch' },
    { secretWord: 'Angst', hintWord: 'Furcht' },
    { secretWord: 'Mut', hintWord: 'Keine Angst' },
    { secretWord: 'Vertrauen', hintWord: 'Glaube an etwas' },
    { secretWord: 'Zweifel', hintWord: 'Unsicherheit' },
    { secretWord: 'Lösung', hintWord: 'Antwort auf Problem' },
    { secretWord: 'Fehler', hintWord: 'Was nicht stimmt' },
    { secretWord: 'Richtig', hintWord: 'Was stimmt' },
    { secretWord: 'Falsch', hintWord: 'Was nicht stimmt' },
    { secretWord: 'Wahr', hintWord: 'Stimmt' },
    { secretWord: 'Gelogen', hintWord: 'Nicht wahr' },
    { secretWord: 'Echt', hintWord: 'Original' },
    { secretWord: 'Falsch (gefälscht)', hintWord: 'Nicht echt' },
    { secretWord: 'Neuigkeit', hintWord: 'Neue Info' },
    { secretWord: 'Geheimnis', hintWord: 'Was niemand wissen soll' },
    { secretWord: 'Nachricht', hintWord: 'Info' },
    { secretWord: 'Brief', hintWord: 'Geschriebene Nachricht' },
    { secretWord: 'E-Mail', hintWord: 'Digitale Nachricht' },
    { secretWord: 'Anruf', hintWord: 'Telefonat' },
    { secretWord: 'Gespräch', hintWord: 'Reden' },
    { secretWord: 'Stimme', hintWord: 'Was man hört' },
    { secretWord: 'Lächeln', hintWord: 'Freundlicher Ausdruck' },
    { secretWord: 'Weinen', hintWord: 'Tränen' },
    { secretWord: 'Schreien', hintWord: 'Laut rufen' },
    { secretWord: 'Flüstern', hintWord: 'Leise reden' },
    { secretWord: 'Lachen', hintWord: 'Fröhlich sein' },
    { secretWord: 'Kuss', hintWord: 'Liebeszeichen' },
    { secretWord: 'Umarmung', hintWord: 'Arme um jemanden' },
    { secretWord: 'Händedruck', hintWord: 'Begrüßung' },
    { secretWord: 'Nicken', hintWord: 'Kopf ja sagen' },
    { secretWord: 'Schütteln', hintWord: 'Kopf nein sagen' },
    { secretWord: 'Handbewegung', hintWord: 'Mit Hand zeigen' },
    { secretWord: 'Gesichtsausdruck', hintWord: 'Zeigt Gefühl' },
    { secretWord: 'Körpersprache', hintWord: 'Körper zeigt Gefühl' },
    { secretWord: 'Stimme', hintWord: 'Ton der Sprache' },
    { secretWord: 'Melodie', hintWord: 'Musik' },
    { secretWord: 'Rhythmus', hintWord: 'Takt der Musik' },
    { secretWord: 'Harmonie', hintWord: 'Schöne Töne' },
    { secretWord: 'Akkord', hintWord: 'Mehrere Töne' },
    { secretWord: 'Orchester', hintWord: 'Viele Musiker' },
    { secretWord: 'Band', hintWord: 'Musiker-Gruppe' },
    { secretWord: 'Sänger', hintWord: 'Singt Lieder' },
    { secretWord: 'Komponist', hintWord: 'Schreibt Musik' },
    { secretWord: 'Tänzer', hintWord: 'Tanzt' },
    { secretWord: 'Ballett', hintWord: 'Tanzkunst' },
    { secretWord: 'Oper', hintWord: 'Musiktheater' },
    { secretWord: 'Drama', hintWord: 'Trauriges Stück' },
    { secretWord: 'Komödie', hintWord: 'Lustiges Stück' },
    { secretWord: 'Tragödie', hintWord: 'Sehr trauriges Stück' },
    { secretWord: 'Roman', hintWord: 'Langes Buch' },
    { secretWord: 'Erzählung', hintWord: 'Kurze Geschichte' },
    { secretWord: 'Gedicht', hintWord: 'Kurzer Text' },
    { secretWord: 'Bilderbuch', hintWord: 'Buch mit Bildern' },
    { secretWord: 'Zeichentrickfilm', hintWord: 'Gemalter Film' },
    { secretWord: 'Dokumentarfilm', hintWord: 'Film über Fakten' },
    { secretWord: 'Science-Fiction', hintWord: 'Zukunftsfilm' },
    { secretWord: 'Fantasy', hintWord: 'Märchenfilm' },
    { secretWord: 'Krimi', hintWord: 'Spannender Film' },
    { secretWord: 'Horror', hintWord: 'Gruselfilm' },
    { secretWord: 'Liebesfilm', hintWord: 'Film über Liebe' },
    { secretWord: 'Komödie (Film)', hintWord: 'Lustiger Film' },
    { secretWord: 'Actionfilm', hintWord: 'Film mit Kampf' },
    { secretWord: 'Abenteuerfilm', hintWord: 'Film mit Reise' },
    { secretWord: 'Trickfilm', hintWord: 'Zeichentrick' },
    { secretWord: 'Netflix', hintWord: 'Filme streamen' },
    { secretWord: 'Twitch', hintWord: 'Gamer live' },
    { secretWord: 'Discord', hintWord: 'Online-Chat' },
    { secretWord: 'Smartphone', hintWord: 'Modernes Handy' },
    { secretWord: 'Tablet', hintWord: 'Flacher Computer' },
    { secretWord: 'Podcast', hintWord: 'Audio-Sendung' },
    { secretWord: 'Influencer', hintWord: 'Bekannte Person online' },
    { secretWord: 'Bitcoin', hintWord: 'Digitales Geld' },
    { secretWord: 'Selfie', hintWord: 'Selbstporträt' },
    { secretWord: 'Emoji', hintWord: 'Kleines Bildsymbol' },
    { secretWord: 'Hashtag', hintWord: 'Schlagwort im Netz' },
    { secretWord: 'Homeoffice', hintWord: 'Arbeit von zu Hause' },
    { secretWord: 'E-Scooter', hintWord: 'Elektrischer Roller' },
    { secretWord: 'Drone', hintWord: 'Fliegende Kamera' },
    { secretWord: 'Smart Home', hintWord: 'Intelligentes Zuhause' },
    { secretWord: 'Streaming', hintWord: 'Videos schauen' },
    { secretWord: 'Gaming', hintWord: 'Spielen am Computer' },
    { secretWord: 'E-Sport', hintWord: 'Profi-Gaming' },
    { secretWord: 'App', hintWord: 'Anwendung auf Handy' },
    { secretWord: 'Cloud', hintWord: 'Daten im Internet' },
    { secretWord: 'Algorithmus', hintWord: 'Rechenregel' },
    { secretWord: 'Roboter', hintWord: 'Maschine mit Funktionen' },
    { secretWord: 'Künstliche Intelligenz', hintWord: 'Computer denkt' },
    { secretWord: 'Virtual Reality', hintWord: 'Virtuelle Welt' },
    { secretWord: 'Augmented Reality', hintWord: 'Erweiterte Realität' },
    { secretWord: 'Webinar', hintWord: 'Online-Seminar' },
    { secretWord: 'Online-Dating', hintWord: 'Partnersuche im Netz' },
    { secretWord: 'Crowdfunding', hintWord: 'Geld sammeln online' },
    { secretWord: 'Fast Fashion', hintWord: 'Schnelle Mode' },
    { secretWord: 'Foodtruck', hintWord: 'Rollende Küche' },
    { secretWord: 'Glamping', hintWord: 'Luxus-Camping' },
    { secretWord: 'Tiny House', hintWord: 'Sehr kleines Haus' },
    { secretWord: 'Vanlife', hintWord: 'Leben im Wohnmobil' },
    { secretWord: 'Work-Life-Balance', hintWord: 'Arbeit und Freizeit' },
    { secretWord: 'Digital Detox', hintWord: 'Pause vom Internet' },
    { secretWord: 'Biohacking', hintWord: 'Körper optimieren' },
    { secretWord: 'Vegan', hintWord: 'Tierfrei essen' },
    { secretWord: 'Fitness-Tracker', hintWord: 'Zeigt Aktivität' },
    { secretWord: 'Smartwatch', hintWord: 'Intelligente Uhr' },
    { secretWord: 'E-Bike', hintWord: 'Elektrisches Fahrrad' },
    { secretWord: 'Carsharing', hintWord: 'Auto teilen' },
    { secretWord: 'Elektroauto', hintWord: 'Auto mit Strom' },
    { secretWord: 'Solarenergie', hintWord: 'Strom von Sonne' },
    { secretWord: 'Windenergie', hintWord: 'Strom von Wind' },
    { secretWord: 'Recycling', hintWord: 'Wiederverwerten' },
    { secretWord: 'Nachhaltigkeit', hintWord: 'Für die Zukunft' },
    { secretWord: 'Klimawandel', hintWord: 'Erde wird wärmer' },
    { secretWord: 'Umweltschutz', hintWord: 'Natur schützen' },
    { secretWord: 'Mülltrennung', hintWord: 'Müll sortieren' },
    { secretWord: 'Plastikmüll', hintWord: 'Abfall aus Plastik' },
    { secretWord: 'Mikroplastik', hintWord: 'Sehr kleines Plastik' },
    { secretWord: 'Artensterben', hintWord: 'Tiere verschwinden' },
    { secretWord: 'Entwaldung', hintWord: 'Bäume abholzen' },
    { secretWord: 'Aufforstung', hintWord: 'Neue Bäume pflanzen' },
    { secretWord: 'Biodiversität', hintWord: 'Vielfalt der Lebewesen' },
    { secretWord: 'Ökosystem', hintWord: 'Lebensgemeinschaft' },
    { secretWord: 'Genetik', hintWord: 'Vererbung' },
    { secretWord: 'DNA', hintWord: 'Bauplan des Lebens' },
    { secretWord: 'Implantat', hintWord: 'Eingesetztes Teil im Körper' },
    { secretWord: 'Telemedizin', hintWord: 'Arzt per Video' },
    { secretWord: 'Mutation', hintWord: 'Veränderung' },
    { secretWord: 'Pandemie', hintWord: 'Weltweite Krankheit' },
    { secretWord: 'Quarantäne', hintWord: 'Isoliert sein' },
    { secretWord: 'Impfstoff', hintWord: 'Mittel gegen Krankheit' },
    { secretWord: 'Therapie', hintWord: 'Behandlung' },
    { secretWord: 'Diagnose', hintWord: 'Krankheit erkennen' },
    { secretWord: 'Symptom', hintWord: 'Krankheitszeichen' },
    { secretWord: 'Heilung', hintWord: 'Gesund werden' },
    { secretWord: 'Ernährung', hintWord: 'Was man isst' },
    { secretWord: 'Diät', hintWord: 'Besondere Ernährung' },
    { secretWord: 'Meditation', hintWord: 'Innere Ruhe finden' },
    { secretWord: 'Yoga', hintWord: 'Körperübungen' },
    { secretWord: 'Stress', hintWord: 'Anspannung' },
    { secretWord: 'Entspannung', hintWord: 'Ruhe' },
    { secretWord: 'Achtsamkeit', hintWord: 'Bewusst sein' },
    { secretWord: 'Glückshormone', hintWord: 'Chemikalien für Freude' },
    { secretWord: 'Immunsystem', hintWord: 'Körperabwehr' },
    { secretWord: 'Vitamin', hintWord: 'Wichtiger Nährstoff' },
    { secretWord: 'Mineralstoff', hintWord: 'Wichtiger Nährstoff' },
    { secretWord: 'Kohlenhydrate', hintWord: 'Energiespender' },
    { secretWord: 'Proteine', hintWord: 'Baustoffe für Körper' },
    { secretWord: 'Fette', hintWord: 'Energiespeicher' },
    { secretWord: 'Netflix', hintWord: 'Streaming-Gigant' },
    { secretWord: 'Bitcoin', hintWord: 'Digitale Münze' },
    { secretWord: 'AirPods', hintWord: 'Ohne Kabel' },
    { secretWord: 'Tinder', hintWord: 'Wisch & Weg' },
    { secretWord: 'Twitch', hintWord: 'Live zusehen' },
    { secretWord: 'Discord', hintWord: 'Gamer-Chat' },
    { secretWord: 'Homeoffice', hintWord: 'Arbeit von Daheim' },
    { secretWord: 'Podcast', hintWord: 'Audio-Blog' },
    { secretWord: 'Meme-Lord', hintWord: 'Internet-Witzbold' },
    { secretWord: 'Diesel-Liebhaber', hintWord: 'A6' },
    { secretWord: 'Hurensohn', hintWord: 'Nutte' },
    { secretWord: 'Lips (Stripclub)', hintWord: 'Ausflug' },
    { secretWord: 'Cookie & Muffin', hintWord: 'Trethupe' },
    { secretWord: 'Döner', hintWord: 'Knoblauch' },
    { secretWord: 'VANS', hintWord: 'Marke' },
    { secretWord: 'Shisha', hintWord: 'Crackie' },
  ];

  private _players: Player[] = [];
  private _secretWord: string = '';
  private _numImposters: number = 0;
  private _giveHintToImposter: boolean = false;
  private _discussionStartingPlayerName: string | null = null; // NEU: Interner Speicher

  constructor() {}

  setupGame(playerNames: string[], numImposters: number, giveHintToImposter: boolean): boolean {
    // ... (bestehende Logik) ...
    // Reset für den Startspieler bei neuem Spielaufbau
    this._discussionStartingPlayerName = null;
    this.discussionStartingPlayerNameSubject.next(null);
    // ... (bestehende Logik) ...
    // Dies stellt sicher, dass bei einem neuen Spiel der vorherige Startspieler gelöscht wird.
    // Der eigentliche Startspieler wird erst am Ende der Enthüllungsphase gesetzt.
    if (playerNames.length === 0 || numImposters <= 0 || numImposters >= playerNames.length) {
      console.error("Invalid game setup parameters");
      return false;
    }

    this._numImposters = numImposters;
    this._giveHintToImposter = giveHintToImposter;

    const randomWordEntry = this.availableWords[Math.floor(Math.random() * this.availableWords.length)];
    this._secretWord = randomWordEntry.secretWord;
    const currentRoundHintWord = randomWordEntry.hintWord;

    this.secretWordSubject.next(this._secretWord);

    this._players = playerNames.map((name, index) => ({
      id: index,
      name: name,
      isImposter: false,
      isRevealed: false,
      hintWord: undefined,
    }));

    let impostersAssigned = 0;
    const playerIndices = this._players.map((_, i) => i);

    while (impostersAssigned < this._numImposters) {
      const randomIndex = Math.floor(Math.random() * playerIndices.length);
      const playerIndexToMakeImposter = playerIndices.splice(randomIndex, 1)[0];

      if (!this._players[playerIndexToMakeImposter].isImposter) {
        this._players[playerIndexToMakeImposter].isImposter = true;
        if (this._giveHintToImposter) {
          this._players[playerIndexToMakeImposter].hintWord = currentRoundHintWord;
        }
        impostersAssigned++;
      }
    }

    this.playersSubject.next([...this._players]);
    this.currentTurnIndexSubject.next(0);
    this.gamePhaseSubject.next('reveal');
    return true;
  }

  revealCardForCurrentPlayer(): void {
    const currentIndex = this.currentTurnIndexSubject.value;
    if (currentIndex < this._players.length) {
      this._players[currentIndex].isRevealed = true;
      this.playersSubject.next([...this._players]);
    }
  }

  nextPlayer(): void {
    const currentIndex = this.currentTurnIndexSubject.value;
    if (currentIndex < this._players.length) {
      this._players[currentIndex].isRevealed = false; // Karte des aktuellen Spielers zurücksetzen
    }

    if (currentIndex + 1 < this._players.length) {
      this.currentTurnIndexSubject.next(currentIndex + 1);
      this.playersSubject.next([...this._players]);
    } else {
      // Alle Spieler haben ihre Rolle gesehen, Übergang zur Diskussionsphase
      this.gamePhaseSubject.next('discussion');
      // Wähle zufällig einen Startspieler für die Diskussion
      if (this._players.length > 0) {
        const randomIndex = Math.floor(Math.random() * this._players.length);
        this._discussionStartingPlayerName = this._players[randomIndex].name;
        this.discussionStartingPlayerNameSubject.next(this._discussionStartingPlayerName);
      } else {
        // Fallback, sollte nicht passieren bei korrektem Spielablauf
        this._discussionStartingPlayerName = null;
        this.discussionStartingPlayerNameSubject.next(null);
      }
    }
  }

  resolveGame(): void {
    this.gamePhaseSubject.next('resolved');
    this._players.forEach(p => p.isRevealed = true);
    this.playersSubject.next([...this._players]);
  }

  startNewRound(): void {
    this._players = [];
    this._secretWord = '';
    this._giveHintToImposter = false;
    this._discussionStartingPlayerName = null; // NEU: Zurücksetzen
    this.discussionStartingPlayerNameSubject.next(null); // NEU: Zurücksetzen
    this.playersSubject.next([]);
    this.secretWordSubject.next('');
    this.currentTurnIndexSubject.next(0);
    this.gamePhaseSubject.next('setup');
  }

  getCurrentPlayer(): Player | null {
    const index = this.currentTurnIndexSubject.value;
    return this._players[index] || null;
  }

  getPlayers(): Player[] {
    return this._players;
  }

  getSecretWord(): string {
    return this._secretWord;
  }
}
